.\"	$Id: priv.1,v 1.6 1997/02/04 06:41:42 lukem Exp $
.\"
.\" Copyright (c) 1996 Telstra Corporation Limited. All rights reserved.
.\" Author: Simon Burge <simonb@telstra.com.au>
.\" Man page converted to mandoc.old by Luke Mewburn <lukem@telstra.com.au>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by Simon Burge, Telstra Corp.
.\" 4. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\"
.TH PRIV 1 "January 29 1997"
.SH NAME
priv \- execute commands as a different user
.SH SYNOPSIS
.B priv
.I command
.RI [ arguments\c
]
.SH DESCRIPTION
.I priv
allows authorised users to execute commands that run as different
users.
.PP
When
.I priv
is invoked, it reads a list of authorised commands from a database
file called
.B /usr/local/etc/priv/\fRusername\fP.
Each line of the database file is a colon-seperated list of fields.
The first two fields must be specified.
Blank lines or lines beginning with a ``#'' character are ignored.
The fields, in order, are:
.PP
.PD 0
.IP
expiry date
.IP
user name to run command as
.IP
flags
.IP
command name
.PD
.PP
The format of the expiry date is YYYYMMDDhhmm.
.PP
The flags field is an integer that contains the following bits:
.PP
.PD 0
.IP
F_SETUID     0000001  allow set-[gu]id programs to run
.IP
F_SYMLINK    0000002  allow symlink as command run
.IP
F_BASENAME   0000004  only check basename of command
.IP
F_LOGLS      0000010  do an 'ls' of the command run
.IP
F_LOGCWD     0000020  log working directory
.IP
F_LOGCMD     0000040  log full command name
.IP
F_LOGTTY     0000100  log user's terminal
.IP
F_BINPATH    0000200  allow any command in given path
.IP
F_GIVEREASON 0000400  ask for reason for running priv
.IP
F_SU         0100000  check su to an account
.PD
.PP
The
.I F_SU
flag enables
.I priv
to authorise an
.IR "su" (8)
command.
In this case, the user name field is the user to
.I su
to, and the command name is ignored.
There should be a link from either
.I su<user>
or
.I su-<user>
to perform an ``su user'' or ``su - user'' as required.
If ``-c command'' is given as arguments to this, then it
is appended to the
.I su
command line.
.PP
The command name may either be a fully qualified path name, or the
command will be run from the user's path.
If the command name is left blank, then the user is allowed to run
.I any
command.
If there is a blank command line in the database file, it should
be placed last.
.PP
If the
.I F_BINPATH
flag is given, then the command name in the configuration file will
be taken as a directory from which any command is valid. If
.I F_BASENAME
is also given, the fully qualified path name won't be necessary.
.PP
.I priv
logs all activity via
.IR "syslog" (3)
using the
.I LOG_AUTH
facility.
All failures contain the string
.I \fR``\fPnot ok\fR''\fP .
.SH FILES
.PD 0
.TP 20
/usr/local/etc/priv
The database directory.
.PD
.SH SEE ALSO
.IR "su" (1)
.SH BUGS
When
.I priv
searchs the
.B PATH
environment variable for a command to run, the checks
are made as the effective user that
.I priv
runs as (root).
Be aware of this when setting permissions on a program.
.SH AUTHORS
Simon Burge <simonb@telstra.com.au> wrote this version
of
.I priv
and 
Luke Mewburn <lukem@connect.com.au> implemented the
.I F_BINPATH
functionality.
.SH HISTORY
A command called
.I priv
was written by Ron Kuris in December 1988, and later modified by
Dan Busarow, DPC Systems, in November 1991.
This version of
.I priv
bears little resemblence to the original command, but keeps the same
name because I like it.
